instance_name  = "lamp_web_server"
instance_type  = "t2.micro"
ami            = "ami-0bd2099338bc55e6d"
key_name       = "lamp_key"
sec_group_name = "lamp_web_server_sg"
db_sec_group_name = "lamb_db_sg"